repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.42.0'
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@>=5.16.0
        -   eslint-config-google@latest
